# Generated by Django 3.0.7 on 2024-06-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                # ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('s1', models.TextField()),
                ('d1', models.TextField()),
                ('s2', models.TextField()),
                ('d2', models.TextField()),
                ('s3', models.TextField()),
                ('d3', models.TextField()),
                ('s4', models.TextField()),
                ('d4', models.TextField()),
                ('s5', models.TextField()),
                ('d5', models.TextField()),
                ('s6', models.TextField()),
                ('d6', models.TextField()),
                ('s7', models.TextField()),
                ('d7', models.TextField()),
                ('s8', models.TextField()),
                ('d8', models.TextField()),
                ('s9', models.TextField()),
                ('d9', models.TextField()),
                ('s10', models.TextField()),
                ('d10', models.TextField()),
                ('memo', models.TextField()),
            ],
        ),
    ]
