# Generated by Django 3.0.7 on 2024-06-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='s1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='s10',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='s2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='s3',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='s4',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='s5',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='s6',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='s7',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='s8',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='s9',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
