# Generated by Django 3.0.7 on 2024-07-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240615_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='d1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='d10',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='d2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='d3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='d4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='d5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='d6',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='d7',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='d8',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='d9',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='s1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='s10',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='s2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='s3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='s4',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='s5',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='s6',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='s7',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='s8',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='s9',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
