# Generated by Django 3.0.7 on 2024-07-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20240706_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='c1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='c10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='c2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='c3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='c4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='c5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='c6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='c7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='c8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='c9',
            field=models.BooleanField(default=False),
        ),
    ]
