# Generated by Django 3.0.7 on 2024-07-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240714_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_1', models.CharField(max_length=255)),
                ('description_2', models.CharField(max_length=255)),
                ('description_3', models.CharField(max_length=255)),
                ('description_4', models.CharField(max_length=255)),
                ('description_5', models.CharField(max_length=255)),
            ],
        ),
    ]
