# Generated by Django 3.0.7 on 2024-07-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20240718_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='description_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='object',
            name='description_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='object',
            name='description_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='object',
            name='description_4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='object',
            name='description_5',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
